### ISSUE TITLE
Minor doc issue with 'cases'

### ISSUE THREAD

**Issue by fecundf** [exodist/Fennec#103]
While looking for "\d" in the source, I saw this documentation for "cases" and was thinking, would like to see an explanation in there about why each case is called "one"

```
    case one => sub { $number = 2 };
    case one => sub { $number = 4 };
    case one => sub { $number = 6 };
    case one => sub { $number = 8 };
```

Is it to group them all together (if so can that be noted in the pod)? or are they meant to be named "two", "four", "six", "eight"?

**Comment by exodist** [comment]
They should be named two four six and eight, good catch.
